export { default as  TestForm} from './TestForm'
export { default as  PageOne} from './Registration/PageOne'
export { default as  PageTwo} from './Registration/PageTwo'
export { default as  PageThree} from './Registration/PageThree'
export { default as  PageFour} from './Registration/PageFour'
export { default as  Thanks} from './Registration/Thanks'
export { default as  Home} from './Home'
export { default as  Login} from './Login/Login'
export { default as  Dashboard} from './Account/Dashboard'
export { default as  ChangePhoto} from './Account/ChangePhoto'
export { default as  Logout} from './Account/Logout'
export { default as  CurrentPassword} from './Account/changePassword/CurrentPassword'
export { default as  NewPassword} from './Account/changePassword/NewPassword'
export { default as  PayFee} from './Account/PayFee'
export { default as  CourseRegistration} from './Account/CourseRegistration'
export { default as  FinalRegisteredCourses} from './Account/FinalRegisteredCourses'
export { default as  FormB} from './Account/FormB'
export { default as  CA} from './Account/CA'
export { default as  FinalResult} from './Account/FinalResult'
export { default as  Transactions} from './Account/Transactions'
export { default as  Info} from './Account/Info'
export { default as  Excel} from './Excel'
export { default as  PageNotFound} from './PageNotFound'
export { default as  ProtectedRoutes} from './ProtectedRoutes'
//test
export { default as  Test} from './Test'

//admin routes
export { default as  Faculty} from './Admin/Faculty'
export { default as  Password} from './Admin/Password'
export { default as  Aim} from './Admin/Aim'
export { default as  UploadCourses} from './Admin/UploadCourses'