name: Deploy COT Buea Client to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2

    - name: Install NPM
      run: sudo apt-get install -y npm

    - name: Install NPM Dependencies
      run: npm install && npm run build

    - name: 📂 Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
